# Generated by Django 2.2.2 on 2019-11-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorPercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.PositiveSmallIntegerField()),
                ('day', models.PositiveSmallIntegerField()),
                ('week', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
