# Generated by Django 2.2.2 on 2019-11-10 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_errorpercentage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ErrorPercentage',
        ),
    ]
