# Generated by Django 2.2.2 on 2019-11-11 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_errorpercentage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ErrorPercentage',
        ),
    ]
