# Generated by Django 2.2.2 on 2019-10-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_server_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='recurringTime',
            field=models.TimeField(null=True),
        ),
    ]
