# Generated by Django 2.2.2 on 2019-10-20 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PingConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('interval', models.PositiveIntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('number_of_requests', models.PositiveIntegerField(default=100)),
                ('timeout', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ping_configuration', to='services.Service')),
            ],
        ),
        migrations.CreateModel(
            name='PingResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_requests', models.PositiveIntegerField(default=100)),
                ('rtt_avg_ms', models.DecimalField(decimal_places=3, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ping_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ping_results', to='ping.PingConfiguration')),
            ],
        ),
    ]
