# Generated by Django 2.2.2 on 2019-10-20 14:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pingresults',
            name='error_messages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=None, size=None),
        ),
    ]
