# Generated by Django 2.2.2 on 2019-10-20 16:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0002_pingresults_error_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pingconfiguration',
            name='interval',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pingconfiguration',
            name='is_active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='pingconfiguration',
            name='number_of_requests',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pingconfiguration',
            name='timeout',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pingresults',
            name='error_messages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None),
        ),
        migrations.AlterField(
            model_name='pingresults',
            name='number_of_requests',
            field=models.PositiveIntegerField(),
        ),
    ]
