# Generated by Django 2.2.2 on 2019-11-11 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0003_auto_20191020_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pingconfiguration',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ping_configurations', to='services.Service'),
        ),
    ]
