# Generated by Django 2.2.7 on 2019-11-23 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0005_delete_errorpercentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoHealthCheckConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('interval', models.PositiveIntegerField()),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='django_health_check_configurations', to='services.Service')),
            ],
        ),
        migrations.CreateModel(
            name='DjangoHealthCheckResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_success', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('django_health_check_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='django_health_check_results', to='django_health_check.DjangoHealthCheckConfiguration')),
            ],
        ),
    ]
