# Generated by Django 2.2.7 on 2019-12-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_health_check', '0002_djangohealthcheckconfiguration_display_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangohealthcheckconfiguration',
            name='email_notifications',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
