# Generated by Django 2.2.7 on 2019-12-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_health_check', '0003_djangohealthcheckconfiguration_email_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='djangohealthcheckconfiguration',
            name='ip',
        ),
        migrations.AddField(
            model_name='djangohealthcheckconfiguration',
            name='url',
            field=models.CharField(default='127.0.0.1:8000', max_length=200),
            preserve_default=False,
        ),
    ]
