# Generated by Django 2.2.2 on 2019-11-04 20:12

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnmpConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('interval', models.PositiveIntegerField()),
                ('is_active', models.BooleanField()),
                ('platform', models.CharField(choices=[('Windows', 'Windows'), ('Linux', 'Linux')], max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('authentication_password', models.CharField(max_length=100)),
                ('privacy_password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snmp_configuration', to='services.Service')),
            ],
        ),
        migrations.CreateModel(
            name='SnmpResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error_messages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('snmp_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snmp_results', to='snmp_v3.SnmpConfiguration')),
            ],
        ),
    ]
