# Generated by Django 2.2.2 on 2019-11-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp_v3', '0002_auto_20191111_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snmpconfiguration',
            name='platform',
            field=models.CharField(choices=[('Linux', 'Linux')], max_length=100),
        ),
    ]
